name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os.runs-on }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
            exec: history_archiver
            artifact_name: history_archiver_linux
          - runs-on: windows-latest
            exec: history_archiver.exe
            artifact_name: history_archiver_windows.exe

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build -r --verbose

    - name: Run tests
      run: cargo test -r --verbose

    - name: Compress
      uses: crazy-max/ghaction-upx@v2
      with:
        version: latest
        files: target/release/${{ matrix.os.exec }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os.artifact_name }}
        path: target/release/${{ matrix.os.exec }}

  build_macos:
    name: Build on macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        profile: minimal
        override: true

    - name: Run tests
      run: cargo test --target=x86_64-apple-darwin -r --verbose

    - name: Build
      run: |
        cargo build --target=aarch64-apple-darwin -r --verbose
        cargo build --target=x86_64-apple-darwin -r --verbose
        lipo -create -output history_archiver_macos target/aarch64-apple-darwin/release/history_archiver target/x86_64-apple-darwin/release/history_archiver

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: history_archiver_macos
        path: history_archiver_macos
